import json, os
os.makedirs("public/data/nodes", exist_ok=True)

biology = [
    {"id":"bio_natural_history","name":"博物学起源","year":"-400","yearRange":[-500,-300],"era":"ancient","domain":"biology","prerequisites":["math_counting"],"description":"亚里士多德对动植物的系统观察和分类，开创了博物学传统，是最早的系统性生物学研究。","importance":4,"tags":["博物","分类","亚里士多德"]},
    {"id":"bio_anatomy_ancient","name":"古代解剖学","year":"-280","yearRange":[-300,-250],"era":"ancient","domain":"biology","prerequisites":["bio_natural_history"],"description":"希罗菲卢斯和埃拉西斯特拉图斯进行了最早的人体解剖，正确描述了神经系统、心脏瓣膜和血管系统。","importance":4,"tags":["解剖","人体","希腊"]},
    {"id":"botany_dioscorides","name":"药物植物学","year":"70","yearRange":[60,80],"era":"ancient","domain":"biology","prerequisites":["bio_natural_history"],"description":"迪奥斯科里德斯的《药物论》详细记录了约600种植物的药用价值，影响了此后1500年的药学实践。","importance":3,"tags":["草药","药物","植物"]},
    {"id":"bio_taxonomy","name":"分类学体系","year":"1758","yearRange":[1750,1770],"era":"renaissance","domain":"biology","prerequisites":["bio_natural_history","math_logic"],"description":"林奈建立的双名法分类体系，用属名和种名为每个物种命名，统一了全球生物学命名标准。","importance":5,"tags":["分类","林奈","双名法"]},
    {"id":"bio_cell_theory","name":"细胞学说","year":"1838","yearRange":[1835,1842],"era":"industrial","domain":"biology","prerequisites":["bio_microscope","bio_taxonomy"],"description":"施莱登和施旺提出的细胞学说认为一切生物都由细胞组成，细胞是生命的基本单位。","importance":5,"tags":["细胞","基本单位","学说"]},
    {"id":"bio_microscope","name":"显微镜发明","year":"1674","yearRange":[1665,1680],"era":"renaissance","domain":"biology","prerequisites":["mat_glass","phys_optics_ancient"],"description":"列文虎克制作的单式显微镜首次观察到细菌、红细胞和精子等微生物，打开了微观生命世界的大门。","importance":5,"tags":["显微镜","微生物","列文虎克"]},
    {"id":"bio_evolution","name":"进化论","year":"1859","yearRange":[1855,1870],"era":"industrial","domain":"biology","prerequisites":["bio_taxonomy","bio_natural_history","math_probability"],"description":"达尔文在《物种起源》中提出自然选择驱动的进化论，解释了生物多样性的起源，是生物学的统一理论。","importance":5,"tags":["进化","自然选择","达尔文"]},
    {"id":"bio_genetics_mendel","name":"孟德尔遗传学","year":"1866","yearRange":[1860,1870],"era":"industrial","domain":"biology","prerequisites":["bio_evolution","math_probability"],"description":"孟德尔通过豌豆杂交实验发现遗传的基本规律——分离定律和自由组合定律，开创了遗传学。","importance":5,"tags":["遗传","豌豆","孟德尔"]},
    {"id":"bio_germ_theory","name":"病原菌学说","year":"1861","yearRange":[1855,1870],"era":"industrial","domain":"biology","prerequisites":["bio_microscope","bio_cell_theory"],"description":"巴斯德和科赫建立的病原菌学说证明传染病由微生物引起，为现代医学和公共卫生奠定了科学基础。","importance":5,"tags":["细菌","病原","巴斯德"]},
    {"id":"bio_embryology","name":"胚胎学","year":"1828","yearRange":[1820,1840],"era":"industrial","domain":"biology","prerequisites":["bio_microscope","bio_cell_theory"],"description":"冯贝尔对胚胎发育的系统研究，发现了哺乳动物卵细胞并建立了比较胚胎学的基本原理。","importance":3,"tags":["胚胎","发育","卵"]},
    {"id":"bio_chromosome","name":"染色体理论","year":"1902","yearRange":[1900,1910],"era":"modern","domain":"biology","prerequisites":["bio_genetics_mendel","bio_cell_theory"],"description":"萨顿和博韦里提出染色体是遗传物质的载体，将孟德尔的遗传因子与细胞学观察联系起来。","importance":5,"tags":["染色体","遗传","减数分裂"]},
    {"id":"bio_dna","name":"DNA双螺旋结构","year":"1953","yearRange":[1950,1955],"era":"modern","domain":"biology","prerequisites":["bio_chromosome","chem_crystallography","phys_quantum_theory"],"description":"沃森和克里克发现DNA的双螺旋结构，揭示了遗传信息的存储和复制机制，开创了分子生物学时代。","importance":5,"tags":["DNA","双螺旋","遗传密码"]},
    {"id":"bio_central_dogma","name":"中心法则","year":"1958","yearRange":[1955,1965],"era":"modern","domain":"biology","prerequisites":["bio_dna"],"description":"克里克提出的分子生物学中心法则描述了遗传信息从DNA到RNA到蛋白质的流动方向，是分子生物学的核心框架。","importance":5,"tags":["中心法则","转录","翻译"]},
    {"id":"bio_genetic_code","name":"遗传密码破解","year":"1966","yearRange":[1961,1968],"era":"modern","domain":"biology","prerequisites":["bio_central_dogma","bio_dna"],"description":"尼伦伯格和霍拉纳等破解了全部64个密码子与20种氨基酸的对应关系，揭示了生命信息的通用语言。","importance":5,"tags":["密码子","氨基酸","通用"]},
    {"id":"bio_restriction_enzyme","name":"限制性内切酶","year":"1970","yearRange":[1968,1975],"era":"modern","domain":"biology","prerequisites":["bio_dna","bio_central_dogma"],"description":"史密斯等人发现的限制性内切酶能精确切割DNA特定序列，是基因工程的基础工具，被称为分子剪刀。","importance":5,"tags":["酶","切割","工具"]},
    {"id":"bio_genetic_eng","name":"基因工程","year":"1973","yearRange":[1972,1976],"era":"modern","domain":"biology","prerequisites":["bio_restriction_enzyme","bio_dna"],"description":"科恩和博耶首次将外源基因导入细菌并成功表达，开创了基因工程时代，使人类能够改造生命的遗传密码。","importance":5,"tags":["基因工程","重组","表达"]},
    {"id":"bio_pcr","name":"PCR技术","year":"1985","yearRange":[1983,1988],"era":"information","domain":"biology","prerequisites":["bio_dna","bio_genetic_eng"],"description":"穆利斯发明的聚合酶链式反应能在体外快速扩增特定DNA片段，使DNA检测和分析变得简单快捷。","importance":5,"tags":["PCR","扩增","DNA"]},
    {"id":"bio_genome_human","name":"人类基因组计划","year":"2003","yearRange":[1990,2003],"era":"information","domain":"biology","prerequisites":["bio_pcr","it_computer","bio_dna"],"description":"历时13年完成的人类全基因组测序，确定了约20000个蛋白编码基因的位置和序列，开启了基因组医学时代。","importance":5,"tags":["基因组","测序","人类"]},
    {"id":"bio_crispr","name":"CRISPR基因编辑","year":"2012","yearRange":[2010,2015],"era":"information","domain":"biology","prerequisites":["bio_genetic_eng","bio_genome_human"],"description":"杜德纳和沙尔庞蒂耶开发的CRISPR-Cas9基因编辑工具，能精确修改基因组中任何位置的DNA序列，革命性地简化了基因编辑。","importance":5,"tags":["CRISPR","编辑","精确"]},
    {"id":"bio_stem_cell","name":"干细胞技术","year":"1998","yearRange":[1995,2005],"era":"information","domain":"biology","prerequisites":["bio_cell_theory","bio_dna"],"description":"汤姆森首次分离人类胚胎干细胞，山中伸弥后来将成体细胞重编程为诱导多能干细胞(iPSC)，开辟了再生医学。","importance":5,"tags":["干细胞","重编程","再生"]},
    {"id":"bio_epigenetics","name":"表观遗传学","year":"1975","yearRange":[1970,2000],"era":"information","domain":"biology","prerequisites":["bio_dna","bio_central_dogma"],"description":"研究不改变DNA序列而影响基因表达的机制，如DNA甲基化和组蛋白修饰，揭示了环境对基因的调控作用。","importance":4,"tags":["表观","甲基化","调控"]},
    {"id":"bio_ecology","name":"生态学","year":"1866","yearRange":[1860,1900],"era":"industrial","domain":"biology","prerequisites":["bio_evolution","bio_taxonomy"],"description":"海克尔提出的生态学概念，研究生物与环境之间的相互关系，后来发展为关注生物多样性和生态系统的重要学科。","importance":4,"tags":["生态","环境","系统"]},
    {"id":"bio_synth_bio","name":"合成生物学","year":"2010","yearRange":[2005,2015],"era":"information","domain":"biology","prerequisites":["bio_crispr","bio_genetic_eng","bio_genome_human"],"description":"通过设计和构建新的生物部件、设备和系统来工程化改造生物体，被认为是21世纪最重要的新兴学科之一。","importance":5,"tags":["合成","设计","工程化"]},
    {"id":"bio_protein_struct","name":"蛋白质组学","year":"1995","yearRange":[1990,2005],"era":"information","domain":"biology","prerequisites":["bio_genome_human","bio_dna"],"description":"大规模研究细胞中所有蛋白质的结构、功能和相互作用，是后基因组时代生物学研究的核心方向。","importance":4,"tags":["蛋白质","组学","功能"]},
    {"id":"bio_virology","name":"病毒学","year":"1898","yearRange":[1890,1910],"era":"industrial","domain":"biology","prerequisites":["bio_germ_theory","bio_microscope"],"description":"伊万诺夫斯基发现烟草花叶病毒，贝杰林克确认病毒是一种新型感染因子，开创了病毒学研究。","importance":4,"tags":["病毒","感染","烟草"]},
    {"id":"bio_immunology","name":"免疫学","year":"1796","yearRange":[1790,1900],"era":"industrial","domain":"biology","prerequisites":["bio_germ_theory"],"description":"从詹纳的牛痘接种到现代免疫学理论，研究机体如何识别和抵御外来入侵者的科学。","importance":5,"tags":["免疫","疫苗","抗体"]},
    {"id":"bio_nervous","name":"神经科学","year":"1906","yearRange":[1890,1920],"era":"modern","domain":"biology","prerequisites":["bio_cell_theory","bio_anatomy_ancient"],"description":"卡哈尔通过显微镜研究揭示神经元是神经系统的基本单位，提出了神经元学说，开创了现代神经科学。","importance":4,"tags":["神经元","大脑","卡哈尔"]},
    {"id":"bio_molecular_bio","name":"分子生物学","year":"1950","yearRange":[1940,1960],"era":"modern","domain":"biology","prerequisites":["bio_dna","bio_genetics_mendel","chem_organic"],"description":"在分子水平上研究生命现象的学科，融合了遗传学、生物化学和生物物理学的方法和理论。","importance":5,"tags":["分子","生物化学","融合"]},
    {"id":"bio_cloning","name":"动物克隆","year":"1996","yearRange":[1995,1998],"era":"information","domain":"biology","prerequisites":["bio_cell_theory","bio_genetic_eng"],"description":"多利羊的诞生证明了成体哺乳动物细胞可以被重编程为全能性，是生物技术的里程碑事件。","importance":4,"tags":["克隆","多利","核移植"]},
    {"id":"bio_bioinformatics","name":"生物信息学","year":"1980","yearRange":[1970,1990],"era":"information","domain":"biology","prerequisites":["it_computer","bio_dna","math_statistics_modern"],"description":"利用计算机科学和统计学方法分析生物数据，特别是基因组序列数据，是现代生物学研究不可或缺的工具。","importance":5,"tags":["信息学","计算","基因组"]},
    {"id":"bio_microbiome","name":"微生物组研究","year":"2007","yearRange":[2005,2015],"era":"information","domain":"biology","prerequisites":["bio_genome_human","bio_germ_theory"],"description":"研究人体内和体表微生物群落对人体健康的影响，发现微生物组与肥胖、免疫和精神疾病等密切相关。","importance":4,"tags":["微生物组","肠道","健康"]},
    {"id":"bio_signal_transduction","name":"细胞信号转导","year":"1970","yearRange":[1960,1985],"era":"modern","domain":"biology","prerequisites":["bio_molecular_bio","bio_cell_theory"],"description":"研究细胞如何接收、处理和响应外界信号的分子机制，是理解癌症、发育和免疫的关键。","importance":4,"tags":["信号","通路","受体"]},
    {"id":"bio_apoptosis","name":"细胞凋亡","year":"1972","yearRange":[1970,1990],"era":"modern","domain":"biology","prerequisites":["bio_cell_theory","bio_molecular_bio"],"description":"细胞程序性死亡机制的发现，揭示了生命通过有序的细胞死亡维持组织稳态和发育的重要过程。","importance":3,"tags":["凋亡","程序性死亡","稳态"]},
    {"id":"bio_rna_interference","name":"RNA干扰","year":"1998","yearRange":[1995,2002],"era":"information","domain":"biology","prerequisites":["bio_central_dogma","bio_genetic_eng"],"description":"小RNA分子能沉默特定基因表达的现象，提供了研究基因功能的新工具和疾病治疗的新策略。","importance":4,"tags":["RNAi","沉默","调控"]},
    {"id":"bio_mrna_vaccine","name":"mRNA疫苗技术","year":"2020","yearRange":[2005,2021],"era":"information","domain":"biology","prerequisites":["bio_pcr","bio_central_dogma","bio_rna_interference"],"description":"利用信使RNA指导细胞产生抗原蛋白的疫苗技术，在新冠疫情中证明了其快速开发和高效保护的能力。","importance":5,"tags":["mRNA","疫苗","新冠"]},
    {"id":"bio_protein_folding","name":"蛋白质折叠预测","year":"2020","yearRange":[2018,2022],"era":"information","domain":"biology","prerequisites":["bio_bioinformatics","it_deep_learning","bio_protein_struct"],"description":"DeepMind的AlphaFold利用深度学习准确预测蛋白质三维结构，解决了困扰生物学界50年的难题。","importance":5,"tags":["AlphaFold","结构预测","AI"]},
    {"id":"bio_neuroplasticity","name":"神经可塑性","year":"1949","yearRange":[1940,1970],"era":"modern","domain":"biology","prerequisites":["bio_nervous","bio_cell_theory"],"description":"大脑在经验和学习影响下改变其结构和功能的能力，推翻了成人大脑不可改变的旧观念。","importance":4,"tags":["可塑性","学习","突触"]},
    {"id":"bio_circadian","name":"生物节律","year":"1971","yearRange":[1960,1985],"era":"modern","domain":"biology","prerequisites":["bio_genetics_mendel","bio_molecular_bio"],"description":"生物体内在的昼夜节律调控机制，2017年诺贝尔奖表彰了周期基因的发现和分子机制的阐明。","importance":3,"tags":["昼夜","节律","时钟"]},
    {"id":"bio_paleontology","name":"古生物学","year":"1812","yearRange":[1800,1830],"era":"industrial","domain":"biology","prerequisites":["bio_natural_history","math_counting"],"description":"居维叶等通过对化石的系统研究，揭示了地球历史上曾存在大量已灭绝的生物，为进化论提供了证据。","importance":4,"tags":["化石","灭绝","地层"]},
    {"id":"bio_mitochondria","name":"内共生学说","year":"1967","yearRange":[1960,1980],"era":"modern","domain":"biology","prerequisites":["bio_cell_theory","bio_evolution"],"description":"马古利斯提出的内共生学说认为线粒体和叶绿体起源于被原始真核细胞吞噬的细菌，解释了真核细胞的起源。","importance":4,"tags":["内共生","线粒体","起源"]},
    {"id":"bio_gmo","name":"转基因生物","year":"1980","yearRange":[1978,1985],"era":"information","domain":"biology","prerequisites":["bio_genetic_eng","bio_restriction_enzyme"],"description":"通过基因工程将外源基因导入生物体，创造自然界不存在的新品种，在农业和医药领域影响深远。","importance":4,"tags":["转基因","生物","改造"]},
    {"id":"bio_single_cell","name":"单细胞测序","year":"2009","yearRange":[2005,2015],"era":"information","domain":"biology","prerequisites":["bio_pcr","bio_genome_human"],"description":"在单个细胞水平上进行基因组、转录组分析的技术，揭示了同一组织中不同细胞类型的异质性。","importance":4,"tags":["单细胞","异质性","测序"]},
    {"id":"bio_organoid","name":"类器官技术","year":"2009","yearRange":[2005,2015],"era":"information","domain":"biology","prerequisites":["bio_stem_cell","bio_cell_theory"],"description":"在体外培养出具有三维结构和部分功能的微型器官，用于疾病建模、药物筛选和个性化医疗。","importance":4,"tags":["类器官","三维","培养"]},
    {"id":"bio_xenobiology","name":"异种生物学","year":"2010","yearRange":[2005,2020],"era":"information","domain":"biology","prerequisites":["bio_synth_bio","bio_genetic_eng"],"description":"设计和创造自然界不存在的生物分子和代谢途径，探索生命的替代化学基础。","importance":3,"tags":["异种","人工","替代"]},
    {"id":"bio_connectome","name":"连接组学","year":"2005","yearRange":[2005,2020],"era":"information","domain":"biology","prerequisites":["bio_nervous","bio_bioinformatics"],"description":"绘制大脑中所有神经元及其突触连接的完整图谱，是理解大脑功能的终极挑战之一。","importance":4,"tags":["连接组","大脑","图谱"]}
]

with open("public/data/nodes/biology.json", "w", encoding="utf-8") as f:
    json.dump(biology, f, ensure_ascii=False, indent=2)
print(f"biology: {len(biology)} nodes")
