import json, os
os.makedirs("public/data/nodes", exist_ok=True)

chemistry = [
    {"id":"chem_alchemy_china","name":"中国炼丹术","year":"-200","yearRange":[-500,300],"era":"ancient","domain":"chemistry","prerequisites":["mat_fire","mat_pottery"],"description":"中国道士在追求长生不老药的过程中积累了大量化学反应知识，包括蒸馏、升华、结晶等操作，是化学的早期源头之一。","importance":4,"tags":["炼丹","中国","蒸馏"]},
    {"id":"chem_alchemy_west","name":"西方炼金术","year":"300","yearRange":[100,800],"era":"ancient","domain":"chemistry","prerequisites":["mat_fire","mat_bronze"],"description":"欧洲和伊斯兰世界炼金术士试图将贱金属转化为黄金的实践，虽目标错误但积累了大量实验技术和化学知识。","importance":4,"tags":["炼金","黄金","实验"]},
    {"id":"chem_distillation","name":"蒸馏技术","year":"800","yearRange":[700,900],"era":"medieval","domain":"chemistry","prerequisites":["chem_alchemy_west","mat_glass"],"description":"伊斯兰炼金术士发展的蒸馏装置和技术，能分离液体混合物，是化学实验和工业生产的基本操作之一。","importance":4,"tags":["蒸馏","分离","酒精"]},
    {"id":"chem_elements","name":"化学元素概念","year":"1661","yearRange":[1650,1680],"era":"renaissance","domain":"chemistry","prerequisites":["chem_alchemy_west","math_axiom"],"description":"波义耳在《怀疑派化学家》中提出元素是不可再分的纯净物的概念，将化学从炼金术分离为真正的科学。","importance":5,"tags":["元素","波义耳","科学"]},
    {"id":"chem_phlogiston","name":"燃素说","year":"1703","yearRange":[1690,1730],"era":"industrial","domain":"chemistry","prerequisites":["chem_elements"],"description":"施塔尔提出的燃素说认为可燃物含有燃素，虽后来被证明错误，但推动了燃烧和氧化反应的深入研究。","importance":3,"tags":["燃素","燃烧","理论"]},
    {"id":"chem_oxygen","name":"氧的发现与氧化理论","year":"1774","yearRange":[1772,1778],"era":"industrial","domain":"chemistry","prerequisites":["chem_phlogiston","chem_elements"],"description":"普里斯特利和舍勒独立发现氧气，拉瓦锡利用这一发现推翻燃素说，建立了正确的氧化燃烧理论，开创了现代化学。","importance":5,"tags":["氧","拉瓦锡","氧化"]},
    {"id":"chem_atomic_theory","name":"原子论","year":"1803","yearRange":[1800,1810],"era":"industrial","domain":"chemistry","prerequisites":["chem_oxygen","chem_elements"],"description":"道尔顿提出的科学原子论认为一切物质由不可分的原子组成，不同元素原子不同，化学反应是原子的重新组合。","importance":5,"tags":["原子","道尔顿","元素"]},
    {"id":"chem_periodic","name":"元素周期律","year":"1869","yearRange":[1865,1872],"era":"industrial","domain":"chemistry","prerequisites":["chem_atomic_theory","math_matrix"],"description":"门捷列夫发现的元素周期律，将元素按原子量排列发现周期性规律，并成功预言了未知元素的存在。","importance":5,"tags":["周期表","门捷列夫","预言"]},
    {"id":"chem_organic","name":"有机化学","year":"1828","yearRange":[1825,1835],"era":"industrial","domain":"chemistry","prerequisites":["chem_atomic_theory","chem_oxygen"],"description":"维勒从无机物合成尿素，打破了有机物只能由生命体产生的观念，开创了有机合成化学的新纪元。","importance":5,"tags":["有机","合成","尿素"]},
    {"id":"chem_structural","name":"化学结构理论","year":"1858","yearRange":[1850,1865],"era":"industrial","domain":"chemistry","prerequisites":["chem_organic","chem_atomic_theory"],"description":"凯库勒和库珀提出的化学键和分子结构理论，特别是苯环结构的发现，使有机化学有了系统的结构语言。","importance":4,"tags":["结构","化学键","苯"]},
    {"id":"chem_stereo","name":"立体化学","year":"1874","yearRange":[1870,1880],"era":"industrial","domain":"chemistry","prerequisites":["chem_structural"],"description":"范特霍夫和勒贝尔提出碳原子的四面体构型理论，解释了分子的空间结构和旋光性，开辟了立体化学领域。","importance":4,"tags":["立体","构型","手性"]},
    {"id":"chem_electrolysis","name":"电解技术","year":"1800","yearRange":[1795,1810],"era":"industrial","domain":"chemistry","prerequisites":["phys_electromagnetism","chem_elements"],"description":"利用电流驱动化学反应的技术，使以前无法分解的化合物得以分解，发现了钠、钾等新元素。","importance":5,"tags":["电解","电流","元素"]},
    {"id":"chem_synthetic_dye","name":"合成染料","year":"1856","yearRange":[1855,1860],"era":"industrial","domain":"chemistry","prerequisites":["chem_organic","chem_structural"],"description":"珀金偶然合成的苯胺紫开创了合成染料工业，使色彩不再是奢侈品，也推动了有机化学和制药业的发展。","importance":4,"tags":["染料","苯胺","合成"]},
    {"id":"chem_haber","name":"哈伯-博施法合成氨","year":"1909","yearRange":[1905,1914],"era":"modern","domain":"chemistry","prerequisites":["chem_elements","phys_thermodynamics_1","chem_catalysis"],"description":"哈伯和博施发明的高压催化合成氨方法，从空气中固定氮气制造化肥，养活了全球近一半人口。","importance":5,"tags":["合成氨","哈伯","化肥"]},
    {"id":"chem_catalysis","name":"催化理论","year":"1835","yearRange":[1820,1850],"era":"industrial","domain":"chemistry","prerequisites":["chem_atomic_theory"],"description":"贝采利乌斯提出的催化概念，催化剂能加速反应但自身不被消耗，后来成为化学工业的核心技术原理。","importance":4,"tags":["催化","反应","工业"]},
    {"id":"chem_polymer_theory","name":"高分子理论","year":"1920","yearRange":[1920,1940],"era":"modern","domain":"chemistry","prerequisites":["chem_organic","chem_structural"],"description":"施陶丁格提出高分子是由共价键连接的长链分子的理论，解释了塑料、橡胶和纤维的本质，开创了高分子化学。","importance":5,"tags":["高分子","聚合","链"]},
    {"id":"chem_nitrocellulose","name":"硝化纤维","year":"1846","yearRange":[1840,1855],"era":"industrial","domain":"chemistry","prerequisites":["chem_organic","chem_elements"],"description":"舍恩拜因偶然发现的硝化纤维(火棉)是最早的爆炸性化合物之一，后来也用于制造赛璐珞和早期电影胶片。","importance":3,"tags":["硝化","爆炸","纤维"]},
    {"id":"chem_radiochemistry","name":"放射化学","year":"1898","yearRange":[1896,1910],"era":"industrial","domain":"chemistry","prerequisites":["phys_radioactivity","chem_atomic_theory"],"description":"居里夫妇建立的放射化学分离和分析方法，发现了钋和镭两种新元素，开创了放射性元素的研究领域。","importance":4,"tags":["放射","镭","居里"]},
    {"id":"chem_isotope","name":"同位素发现","year":"1913","yearRange":[1910,1920],"era":"modern","domain":"chemistry","prerequisites":["chem_radiochemistry","phys_electron"],"description":"索迪发现同位素现象——同一元素存在质量不同但化学性质相同的原子，深化了对原子结构的认识。","importance":4,"tags":["同位素","质量","原子"]},
    {"id":"chem_bond_theory","name":"化学键理论","year":"1916","yearRange":[1913,1920],"era":"modern","domain":"chemistry","prerequisites":["phys_electron","chem_structural"],"description":"路易斯和科塞尔提出的化学键电子理论，用电子的共享和转移解释了原子间的结合力。","importance":5,"tags":["化学键","电子","共价"]},
    {"id":"chem_quantum_chem","name":"量子化学","year":"1927","yearRange":[1926,1935],"era":"modern","domain":"chemistry","prerequisites":["phys_quantum_theory","chem_bond_theory"],"description":"将量子力学应用于化学键和分子结构的研究，海特勒和伦敦首次用量子力学解释了氢分子共价键的本质。","importance":4,"tags":["量子化学","分子轨道","计算"]},
    {"id":"chem_nmr","name":"核磁共振","year":"1946","yearRange":[1940,1955],"era":"modern","domain":"chemistry","prerequisites":["phys_quantum_theory","phys_electromagnetism"],"description":"布洛赫和珀塞尔发现的核磁共振现象，后来成为有机化学结构鉴定最重要的分析工具，也是MRI医学成像的基础。","importance":5,"tags":["NMR","共振","分析"]},
    {"id":"chem_chromatography","name":"色谱法","year":"1906","yearRange":[1900,1920],"era":"modern","domain":"chemistry","prerequisites":["chem_organic"],"description":"茨维特发明的色谱分离技术，利用混合物各组分在固定相和流动相间分配系数不同实现分离，是化学分析的核心方法。","importance":4,"tags":["色谱","分离","分析"]},
    {"id":"chem_crystallography","name":"X射线晶体学","year":"1912","yearRange":[1910,1920],"era":"modern","domain":"chemistry","prerequisites":["phys_electromagnetism","math_fourier"],"description":"布拉格父子发展的X射线衍射法测定晶体结构，后来成为解析蛋白质和DNA三维结构的关键技术。","importance":5,"tags":["晶体","衍射","结构"]},
    {"id":"chem_green","name":"绿色化学","year":"1991","yearRange":[1990,2000],"era":"information","domain":"chemistry","prerequisites":["chem_polymer_theory","chem_catalysis"],"description":"阿纳斯塔斯提出的绿色化学原则，从源头减少化学过程的环境危害，推动了可持续化学工业的发展。","importance":3,"tags":["绿色","可持续","环保"]},
    {"id":"chem_combinatorial","name":"组合化学","year":"1990","yearRange":[1985,1995],"era":"information","domain":"chemistry","prerequisites":["chem_organic","it_computer"],"description":"通过系统组合大量化学构建块快速生成化合物库的方法，加速了新药发现和材料筛选的过程。","importance":3,"tags":["组合","筛选","药物"]},
    {"id":"chem_click_chemistry","name":"点击化学","year":"2001","yearRange":[1998,2005],"era":"information","domain":"chemistry","prerequisites":["chem_organic","chem_catalysis"],"description":"夏普莱斯提出的点击化学概念，使用高效率、高选择性的反应快速构建分子，在药物发现和材料科学中广泛应用。","importance":4,"tags":["点击","高效","模块化"]},
    {"id":"chem_flow_chem","name":"流动化学","year":"2005","yearRange":[2000,2015],"era":"information","domain":"chemistry","prerequisites":["chem_green","chem_catalysis"],"description":"在连续流动反应器中进行的化学合成，比传统批次反应更安全、更高效、更易放大，是制药业的前沿技术。","importance":3,"tags":["流动","连续","制药"]},
    {"id":"chem_mo_theory","name":"分子轨道理论","year":"1932","yearRange":[1930,1940],"era":"modern","domain":"chemistry","prerequisites":["chem_quantum_chem","phys_quantum_theory"],"description":"洪德和马利肯发展的分子轨道理论，将分子中电子视为在整个分子空间中运动的波函数，成功解释了分子的磁性、光谱和反应性。","importance":4,"tags":["分子轨道","理论","量子"]},
    {"id":"chem_asymmetric","name":"不对称合成","year":"1966","yearRange":[1960,1980],"era":"modern","domain":"chemistry","prerequisites":["chem_stereo","chem_catalysis"],"description":"选择性地合成特定手性分子的方法，在制药业中极为重要，因为不同手性的药物分子往往有截然不同的药效。","importance":4,"tags":["手性","催化","不对称"]},
    {"id":"chem_cheminformatics","name":"化学信息学","year":"1970","yearRange":[1965,1985],"era":"information","domain":"chemistry","prerequisites":["it_computer","chem_organic"],"description":"利用计算机和信息技术处理化学数据，建立分子数据库和预测模型，加速药物发现和材料设计。","importance":3,"tags":["信息学","数据库","计算"]},
    {"id":"chem_metal_organic","name":"金属有机框架","year":"1999","yearRange":[1995,2005],"era":"information","domain":"chemistry","prerequisites":["chem_organic","chem_catalysis"],"description":"由金属离子和有机配体组成的多孔晶体材料，具有超高比表面积，在气体储存、分离和催化方面前景广阔。","importance":4,"tags":["MOF","多孔","储氢"]},
    {"id":"chem_photochemistry","name":"光化学","year":"1908","yearRange":[1900,1920],"era":"modern","domain":"chemistry","prerequisites":["phys_quantum_theory","chem_organic"],"description":"研究光与物质相互作用的化学分支，光能驱动化学反应，在摄影、光合成模拟和太阳能利用方面有重要应用。","importance":3,"tags":["光化学","光反应","能量"]},
    {"id":"chem_electrochemistry","name":"电化学","year":"1800","yearRange":[1795,1830],"era":"industrial","domain":"chemistry","prerequisites":["phys_electromagnetism","chem_elements"],"description":"研究化学能与电能相互转化的学科，从伏打电池到现代锂电池和燃料电池，电化学是能源技术的核心。","importance":4,"tags":["电化学","电池","能量"]},
    {"id":"chem_gas_laws","name":"气体定律","year":"1662","yearRange":[1660,1800],"era":"renaissance","domain":"chemistry","prerequisites":["math_calculus","chem_elements"],"description":"波义耳定律、查理定律和阿伏伽德罗假说等气体行为规律，为后来的原子论和热力学提供了实验基础。","importance":4,"tags":["气体","波义耳","理想"]},
    {"id":"chem_acid_base","name":"酸碱理论","year":"1884","yearRange":[1880,1923],"era":"industrial","domain":"chemistry","prerequisites":["chem_electrolysis","chem_ionic_theory"],"description":"从阿伦尼乌斯到布伦斯特-洛里，酸碱理论的发展使化学反应的分类和预测更加系统化。","importance":4,"tags":["酸碱","质子","pH"]},
    {"id":"chem_ionic_theory","name":"电离理论","year":"1884","yearRange":[1880,1890],"era":"industrial","domain":"chemistry","prerequisites":["chem_electrolysis"],"description":"阿伦尼乌斯提出电解质在溶液中电离为离子的理论，解释了溶液的导电性和渗透压等性质。","importance":4,"tags":["电离","离子","溶液"]},
    {"id":"chem_thermochem","name":"化学热力学","year":"1840","yearRange":[1835,1860],"era":"industrial","domain":"chemistry","prerequisites":["phys_thermodynamics_1","chem_elements"],"description":"将热力学定律应用于化学反应，建立了反应热、自由能和化学平衡的定量关系，能预测反应方向和限度。","importance":4,"tags":["热力学","自由能","平衡"]},
    {"id":"chem_kinetics","name":"化学动力学","year":"1850","yearRange":[1850,1900],"era":"industrial","domain":"chemistry","prerequisites":["chem_thermochem"],"description":"研究化学反应速率和机理的学科，从宏观速率方程到微观反应动力学，使化学家能理解和控制反应过程。","importance":4,"tags":["动力学","速率","机理"]},
    {"id":"chem_periodic_modern","name":"现代周期表","year":"1913","yearRange":[1911,1920],"era":"modern","domain":"chemistry","prerequisites":["chem_periodic","phys_electron","chem_isotope"],"description":"莫塞莱用X射线频率确定原子序数后，将元素按原子序数而非原子量排列，修正了门捷列夫周期表中的矛盾。","importance":4,"tags":["周期表","原子序数","莫塞莱"]},
    {"id":"chem_covalent_modern","name":"现代共价键理论","year":"1931","yearRange":[1928,1935],"era":"modern","domain":"chemistry","prerequisites":["chem_quantum_chem","chem_mo_theory"],"description":"鲍林发展的杂化轨道理论，结合量子力学解释了碳的四面体成键和各种分子几何构型。","importance":4,"tags":["杂化","轨道","鲍林"]},
    {"id":"chem_petrochem","name":"石油化学工业","year":"1920","yearRange":[1910,1940],"era":"modern","domain":"chemistry","prerequisites":["chem_organic","chem_catalysis","mat_steel_bessemer"],"description":"以石油为原料生产各种化学品的工业体系，从裂解到聚合，提供了现代塑料、合成纤维和橡胶的原材料。","importance":5,"tags":["石油","裂解","聚合"]}
]

with open("public/data/nodes/chemistry.json", "w", encoding="utf-8") as f:
    json.dump(chemistry, f, ensure_ascii=False, indent=2)
print(f"chemistry: {len(chemistry)} nodes")
